#!/bin/bash
echo 'Enter ngrok authentication token'
echo '-----------------------------------'
read -p "Token:" authtoken
sudo pacman -S --needed git base-devel
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ..
rm -rf yay
yay -S ngrok --noconfirm
sudo echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
sudo systemctl restart sshd.service
ngrok config add-authtoken $authtoken
ngrok tcp 22
